/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Logica.Generador;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class formularioPrincipal extends javax.swing.JFrame {
    
        ArrayList<Double> array = new ArrayList<>();
    /**
     * Creates new form formularioPrincipal
     */
    public formularioPrincipal() throws IOException {
        
     
        initComponents();
        //Seleccionar por defecto el geenerador mixto
        jRadioBMixto.setSelected(true);
        //Esta linea Genera los documentos con los diferentes numeros necesarios para la ejecucion del progerama.
       // Logica.Generador.generarPrimos();
        //Logica.Generador.generarValoresDeA();
        //Logica.Generador.generarValoresdeC();
        Logica.Generador.generarValoresDeAMultiplicativo();
        
        //En este fragmento se cargan los numeros primos que se tienen previamente en un documento con el nombre Primos para el modulo en la 
        //misma carpeta del proyecto. 
        
        List<String> listaNumerosPrimos = new ArrayList<>();
        listaNumerosPrimos= Logica.Generador.cargarPrimos();
        for (int i = 0; i < listaNumerosPrimos.size(); i++) {
            jComboModiulo.addItem(listaNumerosPrimos.get(i));
        }
        
        //Hasta este momento en este punto se cargan para C los mismo valores del modulo, hay qyue corregir.
        
        
        
        
        
        List<String> listaValoresdeC = new ArrayList<>();
        listaValoresdeC= Logica.Generador.cargarValoresC();
//        JOptionPane.showMessageDialog(null, "Array valores c --> "+listaValoresdeC.get(0));
        for (int i = 0; i < listaValoresdeC.size(); i++) {
            jComboAditivo.addItem(listaValoresdeC.get(i));
        }
        
        
        
        
        /*List<String> datos2 = new ArrayList<>();
        datos2=Logica.Generador.cargarValoresA();
        
        
      
        for (String dato : datos2) {
            
                jComboMultiplicativo.addItem(dato);
        }*/
        
        List<String> listaValoresSemilla = new ArrayList<>();
        Logica.Generador.generarValoresDeSemilla();
        listaValoresSemilla = Logica.Generador.cargarValoresSemilla();
        
        for (String semilla : listaValoresSemilla) {
            jComboSemilla.addItem(semilla);
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMixto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBotonGenerar = new javax.swing.JButton();
        jComboModiulo = new javax.swing.JComboBox<>();
        jComboMultiplicativo = new javax.swing.JComboBox<>();
        jComboAditivo = new javax.swing.JComboBox<>();
        jRadioBMixto = new javax.swing.JRadioButton();
        jRadioBMultiplicativo = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioBPuebaPromedio = new javax.swing.JRadioButton();
        jRadioBPruebaFrecuencia = new javax.swing.JRadioButton();
        jRadioBSmirnov = new javax.swing.JRadioButton();
        jRadioBPruebaCorridaArribaAbajo = new javax.swing.JRadioButton();
        jRadioBPruebaPoker = new javax.swing.JRadioButton();
        jBotonValidar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboSemilla = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INGRESANDO LOS PARAMETROS NECESARIOS");

        jLabel2.setText("Seleccione  modulo (m)");

        jLabel3.setText("Seleccione Multiplicativo (a)");

        jLabel4.setText("Seleccione Aditivo (c)");

        jBotonGenerar.setText("Generar numeros y abrir documento");
        jBotonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonGenerarActionPerformed(evt);
            }
        });

        jComboModiulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboModiuloMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboModiuloMouseExited(evt);
            }
        });
        jComboModiulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboModiuloActionPerformed(evt);
            }
        });

        jComboMultiplicativo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboMultiplicativoItemStateChanged(evt);
            }
        });
        jComboMultiplicativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboMultiplicativoMouseClicked(evt);
            }
        });
        jComboMultiplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMultiplicativoActionPerformed(evt);
            }
        });

        jComboAditivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAditivoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioBMixto);
        jRadioBMixto.setText("Metodo Mixto");
        jRadioBMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBMixtoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioBMultiplicativo);
        jRadioBMultiplicativo.setText("Metodo Multiplicativo");
        jRadioBMultiplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBMultiplicativoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRUEBAS ESTADÍSTICAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        buttonGroup2.add(jRadioBPuebaPromedio);
        jRadioBPuebaPromedio.setText("Promedio");
        jRadioBPuebaPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBPuebaPromedioActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioBPruebaFrecuencia);
        jRadioBPruebaFrecuencia.setText("Frecuencia");

        buttonGroup2.add(jRadioBSmirnov);
        jRadioBSmirnov.setText("Smirnov");

        buttonGroup2.add(jRadioBPruebaCorridaArribaAbajo);
        jRadioBPruebaCorridaArribaAbajo.setText("Corrida Arriba Abajo");
        jRadioBPruebaCorridaArribaAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBPruebaCorridaArribaAbajoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioBPruebaPoker);
        jRadioBPruebaPoker.setText("siguiente sprint");

        jBotonValidar.setText("VALIDAR");
        jBotonValidar.setEnabled(false);
        jBotonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonValidarActionPerformed(evt);
            }
        });

        jButton1.setText("VALIDAR TODAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jBotonValidar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioBSmirnov)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioBPuebaPromedio)
                            .addComponent(jRadioBPruebaFrecuencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioBPruebaPoker)
                            .addComponent(jRadioBPruebaCorridaArribaAbajo))))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBPuebaPromedio)
                    .addComponent(jRadioBPruebaCorridaArribaAbajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBPruebaFrecuencia)
                    .addComponent(jRadioBPruebaPoker)
                    .addComponent(jBotonValidar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioBSmirnov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel5.setText("Seleccione Semilla (x0)");

        javax.swing.GroupLayout jPanelMixtoLayout = new javax.swing.GroupLayout(jPanelMixto);
        jPanelMixto.setLayout(jPanelMixtoLayout);
        jPanelMixtoLayout.setHorizontalGroup(
            jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMixtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMixtoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(184, 184, 184))
                    .addGroup(jPanelMixtoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jComboAditivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMixtoLayout.createSequentialGroup()
                        .addComponent(jBotonGenerar)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioBMixto)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBMultiplicativo))
                    .addGroup(jPanelMixtoLayout.createSequentialGroup()
                        .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(1, 1, 1)
                        .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboModiulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboMultiplicativo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboSemilla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanelMixtoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMixtoLayout.setVerticalGroup(
            jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMixtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboModiulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboMultiplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboAditivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonGenerar)
                    .addComponent(jRadioBMixto)
                    .addComponent(jRadioBMultiplicativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Generador de numeros", jPanelMixto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboAditivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAditivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAditivoActionPerformed

    private void jComboMultiplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMultiplicativoActionPerformed

    }//GEN-LAST:event_jComboMultiplicativoActionPerformed

    private void jComboMultiplicativoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboMultiplicativoMouseClicked

    }//GEN-LAST:event_jComboMultiplicativoMouseClicked

    private void jComboMultiplicativoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboMultiplicativoItemStateChanged

    }//GEN-LAST:event_jComboMultiplicativoItemStateChanged

    private void jComboModiuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboModiuloActionPerformed

        int i=4;
        
        
        while(!Logica.Generador.sonRelativamentePrimos(i, Integer.parseInt(jComboModiulo.getSelectedItem().toString()))){
            i++;
        }
        
        jComboMultiplicativo.removeAllItems();
        
        for(int j=1; j<50; j++){
            if(((j-1)%i)==0){
                jComboMultiplicativo.addItem(String.valueOf(j));
            }
        }
                
    }//GEN-LAST:event_jComboModiuloActionPerformed

    private void jBotonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonGenerarActionPerformed
        jRadioBPruebaCorridaArribaAbajo.setForeground(Color.BLACK);
        jRadioBPruebaPoker.setForeground(Color.BLACK);
        jRadioBPuebaPromedio.setForeground(Color.BLACK);
        jRadioBSmirnov.setForeground(Color.BLACK);
        jRadioBPruebaFrecuencia.setForeground(Color.BLACK);
        
        
        int a=0;
        int c=0;
        int m=0;
        int x0=0;
        
        a=Integer.parseInt(String.valueOf(jComboMultiplicativo.getSelectedItem()));
        m=Integer.parseInt(String.valueOf(jComboModiulo.getSelectedItem()));
        c=Integer.parseInt(String.valueOf(jComboAditivo.getSelectedItem()));
        x0=Integer.parseInt(String.valueOf(jComboSemilla.getSelectedItem()));
        if (jRadioBMixto.isSelected()){
          
        if(Logica.Generador.ValidarCampos(a, c, m,x0)){
            try {
                array=Logica.Generador.Mixto(m, a, c,x0);
                jBotonValidar.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{

            JOptionPane.showMessageDialog(null, "El valor de (M) debe ser mayor que (a) y (c)");
        } 
        }else if (jRadioBMultiplicativo.isSelected()){
        if(Logica.Generador.ValidarCampos(a, c, m, x0)){
            try {
                array=Logica.Generador.Multiplicativo(m, a, x0);
                jBotonValidar.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{

            JOptionPane.showMessageDialog(null, "El valor de (M) debe ser mayor que (a) y (c)");
        } 
        }
        

    }//GEN-LAST:event_jBotonGenerarActionPerformed

    private void jBotonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonValidarActionPerformed
           if (jRadioBPuebaPromedio.isSelected()) {
            if(Logica.PruebasEstadisticas.PruebaDePromedio(array)){
                jRadioBPuebaPromedio.setForeground(Color.GREEN);
                /*JOptionPane.showMessageDialog(null, "Los numeros generados NO pueden ser RECHAZADOS, de acuerdo \n"
                                                        +"a la prueba estadistica de promedios");*/
            }else{
                jRadioBPuebaPromedio.setForeground(Color.RED);
              /*JOptionPane.showMessageDialog(null, "Los numeros generados son RECHAZADOS, de acuerdo \n"
                                                        +"a la prueba estadistica de promedios");  */
            }
        }else if (jRadioBPruebaFrecuencia.isSelected()){
            //double a= Logica.PruebasEstadisticas.RetornarCantidad(array);
            if(Logica.PruebasEstadisticas.PruebaDeFrecuencia(array)){
                jRadioBPruebaFrecuencia.setForeground(Color.GREEN);
                /*JOptionPane.showMessageDialog(null, "Los numeros generados NO pueden SER RECHAZADOS, de acuerdo\n"
                                                        +"a la prueba estadistica de frecuencia");*/
        }else{
                jRadioBPruebaFrecuencia.setForeground(Color.RED);
              /*JOptionPane.showMessageDialog(null, "Los numeros generados SON RECHAZADOS, de acuerdo\n"
                                                        +"a la prueba estadistica de frecuencia");  */
            }
        }else if (jRadioBSmirnov.isSelected()){
            //double a= Logica.PruebasEstadisticas.RetornarCantidad(array);
            if(Logica.PruebasEstadisticas.PruebaDeKolmogorov_Smirnov(array)){
                jRadioBSmirnov.setForeground(Color.GREEN);
                /*JOptionPane.showMessageDialog(null, "Los numeros generados NO pueden SER RECHAZADOS, de acuerdo\n"
                                                        +"a la prueba estadistica de smirnov");*/
        }else{
                jRadioBSmirnov.setForeground(Color.RED);
              /*JOptionPane.showMessageDialog(null, "Los numeros generados SON RECHAZADOS, de acuerdo\n"
                                                        +"a la prueba estadistica de smirnov");  */
            }
        }else if (jRadioBPruebaCorridaArribaAbajo.isSelected()){
            //double a= Logica.PruebasEstadisticas.RetornarCantidad(array);
            if(Logica.PruebasEstadisticas.pruebaCorridaArribaAbajo(array)){
                jRadioBPruebaCorridaArribaAbajo.setForeground(Color.GREEN);
                /*JOptionPane.showMessageDialog(null, "Los numeros generados NO pueden SER RECHAZADOS, de acuerdo\n"
                                                        +"a la prueba estadistica corrida arriba abajo");*/
        }else{
                jRadioBPruebaCorridaArribaAbajo.setForeground(Color.RED);
              /*JOptionPane.showMessageDialog(null, "Los numeros generados SON RECHAZADOS, de acuerdo\n"
                                                        +"a la prueba estadistica corrida de arriba abajo");  */
            }
            
        }
    }//GEN-LAST:event_jBotonValidarActionPerformed

    private void jRadioBMultiplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBMultiplicativoActionPerformed
      if (jRadioBMultiplicativo.isSelected()){
          jComboMultiplicativo.removeAllItems();
          for (String string : Logica.Generador.cargarValoresAMultiplicativo()) {
              jComboMultiplicativo.addItem(string);
              
          }
          jComboAditivo.setEnabled(false);
      }else{
          jComboAditivo.setEnabled(true);
      }
    }//GEN-LAST:event_jRadioBMultiplicativoActionPerformed

    private void jRadioBMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBMixtoActionPerformed
       jComboAditivo.setEnabled(true);
       jComboMultiplicativo.removeAllItems();
       for (String string : Logica.Generador.cargarValoresA()) {
              jComboMultiplicativo.addItem(string);
              
          }
       
    }//GEN-LAST:event_jRadioBMixtoActionPerformed

    private void jRadioBPuebaPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBPuebaPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBPuebaPromedioActionPerformed

    private void jComboModiuloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboModiuloMouseExited
    
    }//GEN-LAST:event_jComboModiuloMouseExited

    private void jComboModiuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboModiuloMouseClicked

    }//GEN-LAST:event_jComboModiuloMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // TODO add your handling code here:
        jRadioBPuebaPromedio.setSelected(true);
        jBotonValidar.doClick();
        jRadioBPruebaFrecuencia.setSelected(true);
        jBotonValidar.doClick();
        jRadioBSmirnov.setSelected(true);
        jBotonValidar.doClick();
        jRadioBPruebaCorridaArribaAbajo.setSelected(true);
        jBotonValidar.doClick();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioBPruebaCorridaArribaAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBPruebaCorridaArribaAbajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBPruebaCorridaArribaAbajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formularioPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBotonGenerar;
    private javax.swing.JButton jBotonValidar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboAditivo;
    private javax.swing.JComboBox<String> jComboModiulo;
    private javax.swing.JComboBox<String> jComboMultiplicativo;
    private javax.swing.JComboBox<String> jComboSemilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMixto;
    private javax.swing.JRadioButton jRadioBMixto;
    private javax.swing.JRadioButton jRadioBMultiplicativo;
    private javax.swing.JRadioButton jRadioBPruebaCorridaArribaAbajo;
    private javax.swing.JRadioButton jRadioBPruebaFrecuencia;
    private javax.swing.JRadioButton jRadioBPruebaPoker;
    private javax.swing.JRadioButton jRadioBPuebaPromedio;
    private javax.swing.JRadioButton jRadioBSmirnov;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
